import = ["~/dotfiles/alacritty/tokyonight_storm.toml"]

[env]
TERM = "xterm-256color"
WINIT_UNIX_BACKEND = "x11"

[font]
size = 10

[font.normal]
family = "monospace"

[window]
startup_mode = "Maximized"
