setw -g mode-keys vi

set -g mouse on
set -g extended-keys on
set -g extended-keys-format csi-u
set -g set-clipboard on

set -g automatic-rename on
set -g set-titles on

set -sg escape-time 10

set-option -g focus-events on
set-option -g detach-on-destroy off

bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"

set-hook -g client-session-changed 'run-shell "~/.config/tmux/session-unotify.sh \"#{session_name}\""'

bind -r f run-shell "~/.config/tmux/fzf-session.sh"
bind -r g run-shell "~/.config/tmux/worktree-session.sh"
bind -r a run-shell "~/.config/tmux/opencode-popup.sh"

source-file ~/.config/tmux/tokyonight_night.tmux
source-file ~/.config/tmux/bar.tmux
