env:
  TERM: xterm-256color
  WINIT_UNIX_BACKEND: x11

window:
  startup_mode: Maximized

font:
  normal:
    family: Hack Nerd Font Mono

import:
  - ~/.local/share/nvim/plugged/tokyonight.nvim/extras/alacritty/tokyonight_moon.yml
