env:
  TERM: xterm-256color
  WINIT_UNIX_BACKEND: x11

window:
  startup_mode: Maximized

font:
  normal:
    family: UbuntuMono Nerd Font 

import:
  - ~/.local/share/nvim/site/pack/packer/start/tokyonight.nvim/extras/alacritty/tokyonight_storm.yml

