
#typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=32
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=235
#typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=254
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=254

# Current directory background color.
#typeset -g POWERLEVEL9K_DIR_BACKGROUND=32
typeset -g POWERLEVEL9K_DIR_BACKGROUND=235
# Default current directory foreground color.
typeset -g POWERLEVEL9K_DIR_FOREGROUND=254
