[shell]
app_icon_colorize = true
app_icon_color = "on_surface"

[theme]
mode = "dark"
source = "builtin"
builtin = "Tokyo-Night"

[osd]
position = "bottom_center"
[osd.kinds]
media = false

[wallpaper]
enabled = true
directory = "/home/roy/dotfiles/img/"
[wallpaper.default]
path = "/home/roy/dotfiles/img/bg.jpg"

[bar.default]
position = "top"
font_family = "Lilex Nerd Font Mono"
shadow = false
radius = 0
margin_ends = 0
start = ["workspaces", "active_window"]
end = ["volume", "tray", "bluetooth", "network", "notifications"]

[widget.active_window]
max_length = 800
display = "text_only"

[widget.network]
show_label = false

[widget.workspaces]
show_all_outputs = true
focused_color = "surface_variant"
occupied_color = "surface"
empty_color = "surface"

[dock]
enabled = true
smart_auto_hide = true
reserve_space = false
pinned = ["org.gnome.Nautilus", "google-chrome", "com.mitchellh.ghostty", "discord", "steam"]
