general {
    # Avoid starting multiple lock screens.
    lock_cmd = pidof hyprlock || hyprlock

    # Lock before suspend and turn displays back on after resume.
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # to avoid having to press a key twice to turn on the display.
}

# Lock after 5 minutes idle.
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turn monitors off shortly after locking.
listener {
    timeout = 360
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Suspend after 30 minutes idle.
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
