background = 0xff1a1b26
base = 0xff1a1b26
text = 0xffc0caf5
alternate_base = 0xff16161e
bright_text = 0xffa9b1d6
accent = 0xffc0caf5
accent_secondary = 0xff7aa2f7
font_family = Iosevka Nerd Font
rounding_large = 0
rounding_small = 0
