[tool.poetry]
name = "poetry-instance"
version = "1.8.3"
description = ""
authors = []
license = ""
package-mode = false

[tool.poetry.dependencies]
python = "3.12.6"
poetry = "1.8.3"

[tool.poetry.group.additional.dependencies]
poetry-plugin-dotenv = "^2.4.0"

